solid/specification

webid-oidc/index.bs
webid-oidc/introduction.bs

Sets up skeleton for the initial draft of the solid authentication spec.

Prep authentication spec skeleton.

---

main/http-definitions.bs
main/index.bs

Proposed in https://github.com/solid/specification/issues/200 .

Adds definition for the Accept-Put response header

---

protocol.html

Fix typo in protocol.html

---

protocol.html

I tend to use a new URL for my homepage.

Update my homepage URL

---

notification-subscription-types.html

Resolves https://github.com/solid/notifications/issues/66
This document is deemed to be useful by the Notifications Panel to help implementers discover Subscription Types that are published under https://solidproject.org/TR/ .

Add notification-subscription-types

---

meetings/2022-10-12.md

Add 2022-10-12 agenda and minutes

---

meetings/2022-10-19.md

Add 2022-10-19 agenda and minutes

---

meetings/2022-11-02.md

Add 2022-11-02 agenda and minutes

---

ED/protocol.html

Trust between owners on same origin with multiple storages

---

meetings/2022-12-07.md

Add 2022-12-07 agenda and minutes

---

meetings/2023-01-04.md

Add 2023-01-04 agenda and minutes

---

meetings/2023-01-18.md

Add 2023-01-18 agenda and minutes

---

meetings/2023-01-25.md

Add 2023-01-25 agenda and minutes

---

meetings/2023-02-08.md

Add 2023-02-08 agenda and minutes

---

meetings/2023-02-22.md

Add 2023-02-22 agenda and minutes

---

meetings/2023-03-08.md

Add 2023-03-08 agenda and minutes

---

meetings/2023-03-15.md

Add 2023-03-15 agenda and minutes

---

meetings/2023-03-22.md

Add 2023-03-22 agenda and minutes

---

meetings/2023-04-12.md

Add 2023-04-12 agenda and minutes

---

meetings/2023-05-03.md

Add 2023-05-03 agenda and minutes

---

meetings/2023-05-10.md

Add 2023-05-10 agenda and minutes

---

meetings/2023-05-17.md

Add 2023-05-17 agenda and minutes

---

CONTRIBUTING.md

Closes https://github.com/solid/specification/issues/508

Recommend translation guide and consistent spelling

---

meetings/2023-06-14.md

Add 2023-06-14 agenda and minutes

---

meetings/2023-06-21.md

Add 2023-06-21 agenda and minutes

---

meetings/2023-07-05.md

Add 2023-07-05 agenda and minutes

---

meetings/2023-07-12.md

Add 2023-07-12 agenda and minutes

---

meetings/2023-07-19.md

Add 2023-07-19 agenda and minutes

---

meetings/2023-07-19.md

Update 2023-07-19 minutes

---

meetings/2023-08-02.md

Add 2023-08-02 agenda and minutes

---

meetings/2023-08-09.md

Add 2023-08-09 agenda and minutes

---

meetings/2023-08-16.md

Add 2023-08-16 agenda and minutes

---

meetings/2023-08-30.md

Add 2023-08-30 agenda and minutes

---

meetings/2023-09-06.md

Add 2023-09-06 agenda and minutes

---

meetings/2023-09-11.md

---
[Preview](https://github.com/solid/specification/blob/a055f54ac6ee848582d91b3eb064253870cd2753/meetings/2023-09-11.md)

Add 2023-09-11 agenda and minutes

---

meetings/2023-09-20.md

Add 2023-09-20 agenda and minutes

---

meetings/2023-09-26.md

Add 2023-09-26 minutes

---

index.html

PR resolves https://github.com/solid/specification/issues/553 .
Adding Solid Chat as Work Item to TR as per agreement in [2023-09-27 CG meeting](https://github.com/solid/specification/blob/main/meetings/2023-09-27.md#chat-client-client-spec-new-work-item) with the understanding that copyright and contributors will be updated.
Follow-up PR in https://github.com/solid/chat/pull/3 and https://github.com/solid/chat/issues/2 to be resolved.
Will follow with a merge as there is prior CG consent.

Add Solid Chat as Work Item

---

meetings/2023-10-04.md

Add 2023-10-04 agenda and minutes

---

meetings/2023-10-11.md

Add 2023-10-11 agenda and minutes

---

meetings/2023-10-18.md

Add 2023-10-18 agenda and minutes

---

meetings/2023-11-01.md

Add 2023-11-01 agenda and minutes

---

CONTRIBUTING.md

Further details decisions and processing PRs based on https://www.w3.org/Consortium/Process/#correction-classes

Add section on decisions and processing-pull-requests

---

meetings/2023-11-22.md

I was trying to scribe myself so the minutes are a bit chaotic.
We were also jumping between topics so they are not really chronological.

Minutes 2023-11-22

---

meetings/2023-12-13.md

Add 2023-12-13 agenda and minutes

---

ED/protocol.html
ED/qa.html
LICENSE.md

Created PR for awareness. Aligned with https://www.w3.org/community/solid/charter/ .

Update Solid QA copyright and license

---

meetings/2024-02-21.md

Add meeting agenda 2024-02-21

---

meetings/2024-03-13.md

Add meeting agenda 2024-03-13

---

meetings/2024-04-03.md

Add meeting agenda 2024-04-03

---

meetings/2024-05-29.md

Add meeting agenda 2024-05-29

---

meetings/2024-06-05.md

Add meeting agenda 2024-06-05

---

meetings/2024-07-03.md

Add meeting agenda 2024-07-03

---

meetings/2024-08-21.md

Add agenda 2024-08-21

---

meetings/2024-09-18.md

Add agenda 2024-09-18

---

meetings/2024-11-06.md

Add meeting agenda 2024-11-06

---

index.html

As discussed in today's CG call.
CC @lecoqlibre @elf-pavlik

Add ERP c2c work item
