solid/specification

- main/index.bs
- main/introduction.bs
- main/resource-access.bs
- main/security.bs
> Add CORS section

- main/resource-access.bs
- main/security.bs
Issues such as https://github.com/inrupt/wac-ldp/issues/114 indicate that we want to explicitly refer to the HTTP specification.
I am following the intent of the current draft specs and implementations, with the exception of:
- suggesting HTTP/2 (only in addition to HTTP/1.1)
- suggesting instead of requiring range requests (unclear whether https://github.com/solid/node-solid-server/issues/442 was a suggestion or requirement)
Feedback most welcome.
> Add HTTP section

- main/introduction.bs
- main/resource-access.bs
- main/security.bs
Commits include some of the criteria from the issues based on rough consensus. Topics vary but some emphasis on "resource access".
The request for review is to confirm what's captured here is accurate ie. the raw criteria. Text needs to be revised and re-organised in the spec but that is intended to be addressed in a future PR.
Edit: I'd like to suggest that technical objections to the criteria should be taken up in the referenced issues in order to better preserve the rationale in context of how they came through.
> Some criteria based on rough consensus

- .travis.yml
- main/index.bs
- main/resource-access.bs
Included in this pull is a [candidate proposal](https://github.com/solid/process#reviewing-proposals) from the [data interoperability panel](https://github.com/solid/data-interoperability-panel/tree/master/resource-metadata) for the handling of resource metadata in a Solid server. Specifically, this proposal introduces a mechanism for linking to metadata about resources in the Solid Ecosystem, and enumerates a set of reserved metadata types.
Remaining issues have been identified inline. Most noticeable will be the need to identify the contents of identified metadata types. The panel felt it was appropriate to raise those discussions to the editorial level first, as the various metadata types cross panel boundaries.
It should be noted that a significant amount of review and iteration was …
> Initial auxiliary resources draft

- main/resource-access.bs
Criteria for servers to apply heuristics to determine a request's resource type. Based on consensus at https://github.com/solid/specification/issues/128#issuecomment-573033297
> Add heuristic to determine resource type

- main/resource-access.bs
In response to the following (and possibly other) issues on how read, append, write and delete operations work in context of Web Access Control:
* https://github.com/solid/specification/issues/33
* https://github.com/solid/specification/issues/37
* https://github.com/solid/specification/issues/39
* https://github.com/solid/specification/issues/39
* https://github.com/solid/specification/issues/40
* https://github.com/solid/specification/issues/41
* https://github.com/solid/specification/issues/42
* https://github.com/solid/specification/issues/43
* https://github.com/solid/specification/issues/46
* https://github.com/solid/specification/issues/60
* https://github.com/solid/specification/issues/68
* https://github.com/solid/specification/issues/72
* …
> Reading and Writing resources

- main/resource-access.bs
Initial requirement on Representations. This particular requirement involves issues:
* https://github.com/solid/specification/issues/45
* https://github.com/solid/specification/issues/69
* https://github.com/solid/specification/issues/109
* https://github.com/solid/specification/issues/195
Will update this space to include related issues.
Feedback on making this more readable is most welcome.
> Add payload and representations in RDF

- main/http-definitions.bs
- main/index.bs
With intent to submit to IANA for review, approval, and inclusion in the IANA Link Relations registry.
* https://github.com/solid/specification/issues/54
* https://github.com/solid/web-access-control-spec/issues/21
> Add section for acl Link relation type

- main/resource-access.bs
There is a slight discrepancy in the spec where it recommends:
>Clients who want the server to assign a URI of a resource, MUST use the POST request.
and
>Servers MUST create intermediate containers and include corresponding containment triples in container representations derived from the URI path component of PUT, POST and PATCH requests.
For example, say `/foo/` exists, it is not entirely clear what happens with:
```
POST /foo/bar/baz/
Link: rel=type LDPC
```
The expectation would've been along the lines of creating a new container with a server determined name eg. `/foo/bar/baz/qux/`.
However, that raises a bit of a question as to why `bar/baz/` are created where client determines the name.
In order to minimise confusion and to keep things consistent, the PR restricts `POST` to target …
> Restrict POST target to existing resources

- main/resource-access.bs
In response to the following (and possibly other) issues on the relationship between data pod and Storage, determining and discovering storage:
* https://github.com/solid/data-interoperability-panel/issues/10
* https://github.com/solid/specification/issues/153
* https://github.com/solid/specification/issues/197
Special shoutout to @megoth and co sharing their implementation experience as well as documenting their findings: https://megoth.inrupt.net/public/SolidDataBrowser/pod-info.html ( https://web.archive.org/web/20201106145438/https://megoth.inrupt.net/public/SolidDataBrowser/pod-info.html ). More of this please! Thanks.
> Requirements pertaining to storage

- main/resource-access.bs
The n-dash has been used before, therefore it should be changed here as well.
> Use consistent dash

- main/authorization.bs
In response to the following (and possibly other) issues on the `WAC-Allow` header:
* https://github.com/solid/specification/issues/170
* https://github.com/solid/specification/issues/171
* https://github.com/solid/specification/issues/181
Future considerations:
In order for this HTTP header to be reusable by any access control system, we can consider changing the header field-name as well as the parameters and values.
Introduce new modes eg. "delete", if and when needed.
At the moment, access modes corresponds to the ones defined in the ACL ontology (also kept in context of the Web Access Control section), however, we can relax this with some editing.
There is also the alternative approach to using URIs instead of human-friendly terms for the allowed access modes. While that'd be precise …
> Add WAC-Allow definition and requirements

- .github/workflows/copy-to-website.yml
Whenever someone pushes to master of the `/specification` repo, it will clone the repo's contents to `solid/solidproject.org` at the folder `/root/TR/`.
This will be a DIRECT COMMIT TO MASTER on `solid/solidproject.org`.
Note: merging this PR will begin this functionality.
> Created automated push to site action

- protocol.html
As per https://gitter.im/solid/specification?at=60101295d8bdab47395e6775 .. the decision was to simplify WAC-Allow parsing by only using quoted access modes.
> Update WAC-Allow access-modes syntax

- protocol.html
This PR introduces minimal changes necessary to clarify discovery, reading and writing of ACL and Description resources (specifically under Auxiliary Resources) - to be consistent with the rest of the Protocol. Further re-organisation of content is left for future PRs.
The PR also address the key concerns raised in PRs https://github.com/solid/specification/pull/248 and https://github.com/solid/specification/pull/250 . If accepted and merged, then those two PRs should be closed immediately.
---
Access controls that are required to read-write ACL resources are specified by the WAC specification. The outer Protocol - in this case the Auxiliary Resources section - must take care to not introduce potential confusion or conflicts.
As it stands, access controls required to read-write Resource …
> Clarify discovery, reading, and writing auxiliary resources

- protocol.html
I found the language to be inaccurate (`PUT and PATCH requests`), but also not testable.
There is no way to test the desires of a client; but we can test the behavior of the server.
So, in my opinion, it's the server that `MUST`, not the client.
> Make resource creation more exact and testable

- protocol.html
Hello Reviewers,
In response to the following (and possibly other) issues on the notion of "owner":
* https://github.com/solid/specification/issues/67
* https://github.com/solid/specification/issues/132
* https://github.com/solid/specification/issues/153
* https://github.com/solid/specification/issues/197
If describing the relationship between Solid data pod / storage "owner" and AWWW's "URI ownership" is required, it can be done in another PR.
On merge of this PR, a follow-up PR will be made to the https://github.com/solid/vocab/ repository requesting to add and define the term "owner" in the Solid Terms vocabulary: `http://www.w3.org/ns/solid/terms#owner`. Proposal (derived from http://www.w3.org/ns/auth/acl#owner ):
```turtle
solid:owner
a rdf:Property ;
dc:issued …
```
> Add notion of "owner" and requirements

- index.html
[The link to Shape Trees Specification in Solid Spec index](https://solidproject.org/TR/#work-item-technical-reports) leads to 404.
https://shapetrees.github.io/specification/spec --> https://shapetrees.org/TR/specification/
There also seems to exist a [Shape Trees Primer](https://shapetrees.org/TR/primer/), which is not (yet) included in the same [list of specs and primers in Solid Spec](https://solidproject.org/TR/#work-item-technical-reports).
> Fix a defunct link to Shape Trees specification

- protocol.html
Created this PR for visibility. Will merge as it is deemed to be an editorial follow-up of WAC ED: https://github.com/solid/web-access-control-spec/pull/83 .
Note: although the WAC ED includes the `acl` link relation type and the `wac-allow` header definitions, I've intentionally kept them in the Protocol. Will followup in WAC ED and specify how it uses those definitions.
> Editorial: update with the WAC spec as authoritative

- 2021/wac-20210711.html
- protocol.html
- wac.html
- wac.timemap.ttl
Follows https://github.com/solid/web-access-control-spec/pull/83
A draft version of the WAC specification for publication:
* Contents of the `wac.html` file publicly accessible from https://solidproject.org/TR/wac (Original resource)
* Contents of the `2021/wac-20210711.html` file publicly accessible from https://solidproject.org/TR/2021/wac-20210711 (Versioned resource) -- Solid Project's URI Persistency Policy applies ( https://solidproject.org/terms#uri-persistence-policy ) 
* Contents of the `wac.timemap.ttl` file publicly accessible from https://solidproject.org/TR/wac.timemap (Timemap)
> Publish TR/wac

- index.html
- protocol.html
The Solid-OIDC specification has been split off from the Authentication Panel repository. The new URL is https://solid.github.io/solid-oidc/ and the corresponding repository is at https://github.com/solid/solid-oidc
> Adjust URL for Solid-OIDC specification

- meetings/template.md
This is a minutes template that can be used in W3C Solid CG meetings.
* Past meeting with minor differences to PR'd: https://github.com/solid/notifications-panel/blob/main/meetings/2021-09-16.md
* Template in use, e.g., in notifications-panel: https://github.com/solid/notifications-panel/blob/main/meetings/template.md
* Upcoming meeting, e.g., in live editor: https://hackmd.io/u37sG1o3TMyahXf6iRVMeQ
The template was derived from https://gitter.im/solid/specification?at=600eda39ac653a0802df61f7 and practice in panels.
> W3C Solid Community Group meeting minutes template

- protocol.html
The URI owner may not have delegated authority to the server.
> Remove optional advisement relying on delegation of authority

- meetings/README.md
Some notes below. Not required reading for the PR.
Using the W3C Process as guide, the recommendation is that the minutes of distributed meetings should be available after 48 hours. As far as I can tell from documentation related to scribing and minutes - and personal experience - groups come to an agreement about what's on record - how exactly they agree on the record is not specified. W3C groups use different approaches (and tools), e.g., minutes are shortly available after the meeting, draft minutes are generated, and approved by the group, and in other ways. I've pinged people as well as W3C (on IRC) for pointers and experiences but so far it seems that there is no formal process for agreeing to what has been minuted, and corrections are rare. Will share info once I know more.
Edit: …
> W3C Solid Community Group Meeting Guidelines

- ED/protocol.html
Related issue: https://github.com/solid/specification/issues/356
Not all servers will be configured to receive/respond to `OPTIONS *` (`asterisk-form`). Clients can't rely on all servers (be instructed by their respective URI owners) allowing the request.
Checking for `Accept-*` header options should be possible with `OPTIONS` targeting a resource (`origin-form` or `absolute-form`).
> Remove server-options-asterisk-accept-headers. Add OPTIONS to server-accept-headers

- oidc-primer.html
Created this PR for awareness for everyone and the Editors of Solid-OIDC Primer so they can follow-up elsewhere. Merging.
@jaxoncreed @matthieubosquet @acoburn
---
[Preview](https://htmlpreview.github.io/?https://github.com/solid/specification/blob/5f12d4c734ce71d31e74c872f1b97475f11593f1/oidc-primer.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2Fmain%2Foidc-primer.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2F5f12d4c734ce71d31e74c872f1b97475f11593f1%2Foidc-primer.html)
> Add missing 'Primer' to Solid-OIDC in title/heading

- index.html
This PR's purpose is to introduce WebID Profile as a work item. 
See: https://github.com/solid/webid-profile/issues/15
---
[Preview](http://htmlpreview.github.io/?https://github.com/solid/specification/blob/e4f738436cbcd22bdf9c6f6e267978b2781efc39/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2Fmain%2Findex.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2Fe4f738436cbcd22bdf9c6f6e267978b2781efc39%2Findex.html)
> Add WebID Profile as work item

- ED/protocol.html
Creating this PR (updates Editor's Draft) for awareness; request for comments, implementation feedback, intent to implement.
The PR adds requirements for discovering a storage description resource and its description. It is based on potential solution to the use cases provided in https://github.com/solid/specification/issues/355 (including implementation feedback) , as well as agreement by the Editors Team:
* https://github.com/solid/specification/blob/main/meetings/2022-06-15.md#storage-description
* https://github.com/solid/specification/blob/main/meetings/2022-06-08.md#agenda-review
* https://github.com/solid/specification/blob/main/meetings/2022-06-01.md#storage-description
> Add server-storage-description server-storage-description-resource storage-description-statements

- ED/protocol.html
This adjusts the Solid Protocol ED to require the new [Solid Notification Protocol](https://solidproject.org/TR/notifications-protocol).
As part of this change, all references to the old WebSocket mechanism move to non-normative statements, encouraging existing implementations to continue to support backwards compatibility, as appropriate.
This change also modifies the existing "Notifications" section title to "Linked Data Notifications" in order to avoid confusion between sections 6 and 7.
> Add requirement for Solid Notification Protocol

- README.md
This is a proposal to have a weekly meeting for the W3C Solid Community Group (CG) as mentioned in the solid/specification Gitter chat [1] and in the W3C TPAC 2022 meeting [2].
There is an event that's drafted [3] - scheduled for Wednesdays at 14:00 UTC - for the CG calendar [4]. We will not observe daylight savings time.
Anyone may join the meeting. Participants must abide by the terms and spirit of the W3C Code of Ethics and Professional Conduct (CEPC) [5].
The Chair will propose and approve the agenda for each meeting. Participants are welcome to review and propose agenda topics.
The Solid Technical Reports Contributing Guide [6] describes different ways to contribute and follow the Solid project.
The CG Meeting Guidelines [7] describes how to participate and record meetings.
There is …
> Add W3C Solid CG weekly meeting to Participation

- ED/protocol.html
Issue https://github.com/solid/specification/issues/44
> Add constraint discovery for client errors

- ED/protocol.html
Follows https://github.com/solid/specification/pull/365 .
Created PR for awareness. Merging with the understanding that it is editorial since the term is not used in this document or referred by other Work Items.
> Removed unused data-pod definition

- ED/protocol.html
This PR develops the under-specified `#conformance` model. Resolves https://github.com/solid/specification/issues/282 .
The work herein follows the guidelines in https://www.w3.org/TR/spec-variability/ and https://www.w3.org/TR/qaframe-spec/ , and applies http://www.w3.org/ns/spec# . Future PRs will describe the other dimensions of variability and more specificity as needed (see also https://github.com/solid/specification/issues/480 ).
The table below can be used by reviewers to look up the changes introduced by this PR:
* Target: Unit of information that's changed.
* Correction class: https://www.w3.org/2021/Process-20211102/#correction-classes
* `1`: No changes to text content
* `2`: Corrections that do not affect conformance
* `3`: Corrections that do not add new features (specifically …
> Update conformance model

- ED/qa.html
This Work Item describes the Solid QA policy, processes, and procedures. The document is Version 0.1.0 Editor's Draft and proposed to be published at https://solidproject.org/ED/qa .
It is one of the deliverables of the Solid Test Suite Panel Charter: https://github.com/solid/process/blob/main/test-suite-panel-charter.md
---
[Preview](https://htmlpreview.github.io/?https://github.com/solid/specification/blob/53cbcefa5a93c444ad40798d01f0fa1287e4d3d8/ED/qa.html)
> Add Solid QA

- 2022/protocol-20221231.html
- protocol.timemap.html
Add Solid Protocol, Version 0.10.0.
`#change-log` section indicates changes since [TR/2022/protocol-20211217](https://solidproject.org/TR/2021/protocol-20211217).
---
[Preview](http://htmlpreview.github.io/?https://github.com/solid/specification/blob/dbefa0d6bf82baaf1bd5305c38845ac6bc491afa/protocol.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2F8efc7b5e67bbaf005412aec8855989f1af19067f%2Fprotocol.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2Fdbefa0d6bf82baaf1bd5305c38845ac6bc491afa%2Fprotocol.html)
> Add TR/2022/protocol-20221231

- ED/qa.html
Follows action of https://github.com/solid/test-suite-panel/blob/main/meetings/2023-02-21.md#specify-requirements-and-criteria-for-publishing-test-summaries-and-reports
---
[Preview](http://htmlpreview.github.io/?https://github.com/solid/specification/blob/8f3570f93ac18d19c9614e08be02e59245eac34b/ED/qa.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2F18881a4eb2d2f4e49ddaac8390fc355d7467d36b%2FED%2Fqa.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2F8f3570f93ac18d19c9614e08be02e59245eac34b%2FED%2Fqa.html)
> Update test-report-description test-case-description test-assertion-description

- ED/protocol.html
- ED/qa.html
PR'd to create some awareness that the latest W3C Process as of this writing is https://www.w3.org/2023/Process-20230612/ .
Merging as the changes only referred by a non-normative section.
> Update to W3C Process 20230612

- ED/protocol.html
Happy solstice!
This PR is a https://www.w3.org/2023/Process-20230612/#class-2 change in the specification updating the #changelog section in the following ways:
* Detailed use of language and links from W3C Process Document's [Classes of Changes](https://www.w3.org/2023/Process-20230612/#correction-classes) in the changelog.
* Uses a table with columns Change Class, Subject, and Description to further detail editorial, substantive, registry changes in the specification since the previous version. Each row in the table corresponds to a specific "change".
* Adds link to list of issued addressed.
* Adds link to W3C diff service between this version and previous version.
* Adds link to GitHub for detailed log of changes.
* Adds link to changelog of previous version to discover earlier …
> Update changelog detailing Classes of Changes

- ED/qa.html
Follows actions of https://github.com/solid/test-suite-panel/blob/main/meetings/2023-05-16.md
* Update technical-report-description (for the discovery of implementation report and test suite)
* Update test-suite-description (for the discovery of test cases)
* Add implementation-report-description
---
[Preview](http://htmlpreview.github.io/?https://github.com/solid/specification/blob/bb84886d41ae9b9487c384cbc1ae2ad25b3645f5/ED/qa.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2F0a14f9b6011d8db394cbd26e3a7b09037715b4d9%2FED%2Fqa.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2Fbb84886d41ae9b9487c384cbc1ae2ad25b3645f5%2FED%2Fqa.html)
> Add discovery and descriptions for implementation report, test suite, test case

- CONTRIBUTING.md
The proposed CG charter includes a process for [new work item proposals](https://github.com/solid/process/blob/7a8cfc55edaaf9de26252976fa8365d7c884bdc7/solid-cg-charter.md#new-work-item-proposal) (NWIP).
As mentioned, "some of this information could be moved to other documents". So, this PR moves NWIP from proposed Charter to the [Contributing Guide](https://github.com/solid/specification/blob/main/CONTRIBUTING.md).
Merging this PR should follow be followed with committing suggestion to refer to NWIP in Contributing Guide: https://github.com/solid/process/pull/323/files#r1267917483
> Add Work Items section

- ED/qa.html
Following up on https://github.com/solid/specification/issues/471, this PR updates the references to HTTP RFCs from 7230/7540 to 9110/9113. While these are normative references, this has no impact, since they are not actually used in the draft.
If there still are any concerns about normative changes, you can check the changelogs here:
- [RFC7230 => RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html#appendix-B.2)
- [RFC7540 => RFC9113](https://www.rfc-editor.org/rfc/rfc9113.html#name-changes-from-rfc-7540)
Target | Correction class | Note
-- | -- | --
#bib-rfc7231 | [1](https://www.w3.org/2021/Process-20211102/#class-1) (no content change, only bibliography) | removes (unused) reference to obsolete RFC7231
#bib-rfc7540 | [1](https://www.w3.org/2021/Process-20211102/#class-1) (no content …
> Feat: update HTTP refs in QA

- index.html
Going through the TRs I noticed the link to the SAI primer resulted in a 404. I believe this has not been updated since SAI split the primer into separate parts aimed at the different conformance classes. Can you confirm this, @elf-pavlik?
I also corrected the status of the primer(s), which said ED but is in fact UD according to the documents themselves.
Target | Correction class | Note
-- | -- | --
#work-item-technical-reports | [2](https://www.w3.org/2021/Process-20211102/#class-2) | update broken link
#work-item-technical-reports | [2](https://www.w3.org/2021/Process-20211102/#class-2) | correct displayed draft status
_(The TR table does not containe more finegrained IDs, so could not put more detail in correction table above.)_
[HTML …
> Fix: update SAI primer link

- ED/protocol.html
- ED/qa.html
PR updates the SotD section given that the [Solid CG Charter](https://www.w3.org/community/solid/charter/) supersedes Solid Process.
> Remove mention of Solid Process from SotD

- ED/protocol.html
- LICENSE.md
Created PR for awareness. Aligned with https://www.w3.org/community/solid/charter/ .
> Update copyright and license

- ED/protocol.html
This PR is a https://www.w3.org/2023/Process-20230612/#class-2 change in the specification updating the #privacy-considerations section by adding a consideration for #consider-webid-profile . It describes that the owner of a WebID Profile (in a Solid storage) ultimately decides what to include or exclude in its description, however, there may be other resources which may directly or indirectly reveal information, so the owners of the WebID are advised to take that into account.
[Preview](https://htmlpreview.github.io/?https://github.com/solid/specification/blob/e0cd730397700953eccb6a44edc3b0a93c3d38a4/ED/protocol.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fspecification%2Fa5e7295919f9c679d335e7e3da2388a7f63c5f93%2FED%2Fprotocol.htm …
> Add consider-webid-profile

- CONTRIBUTING.md
- meetings/README.md
- meetings/template.md
This PR adds document status (modified and reason) to documents pertaining to the Solid CG. It follows a 2023-10-10 Solid CG meeting actions with the goal to clean-up / update references to CG's work. A related change was also made by https://github.com/solid/process/pull/331 .
> Add document status to guides, templates

- meetings/2024-05-21.md
> Add meeting minutes 2024-05-21 (Special Topic Meeting)

- ED/protocol.html
wrong heading level in section 1.4.1, which makes it appear as 1.4 in the body (the ToC is correct, though).
> fix wrong heading level

- ED/protocol.html
This PR makes a [correction class 4 change](https://www.w3.org/2023/Process-20231103/#class-4):
* Add server requirement https://solidproject.org/ED/protocol#server-last-modified-includes to include the `Last-Modified` header field.
In an nutshell, the `Last-Modified` header field is useful for clients in a number of ways. RFC 9110 only goes as far as setting a SHOULD requirement level for servers, e.g., https://www.rfc-editor.org/rfc/rfc9110#name-last-modified , https://www.rfc-editor.org/rfc/rfc9110#section-15.3.1-5 . This PR makes it a MUST as there is already precedent of its use, and ensures that clients can rely on it where applicable:
---
I'm generally considering this PR to be a class 4 change because the `Last-Modified` header wasn't explicitly required in the Solid Protocol, …
> Add server to support Last-Modified header field

- protocol.html
> Fix typo: Link to LDP, not LDN

- meetings/2025-09-24.md
Documented the W3C Solid Community Group meeting held on September 24, 2025, including attendance, action items, and discussions on various topics.
> Add minutes for W3C Solid CG meeting on 2025-09-24
